import '../styles/main.css';
import 'bootstrap/dist/css/bootstrap.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { persistor, Store } from '../redux/store';
import { PersistGate } from 'redux-persist/integration/react';
import { Provider } from 'react-redux';
import Hearder from '../components/hearder/hearder';
import Head from 'next/head';
import Footer from '../components/footer/footer';


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>INNHANH79</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Provider store={Store}>
        <PersistGate loading={null} persistor={persistor}>
          <Hearder />
          <Component {...pageProps} />
          <Footer />
          <ToastContainer
            position="bottom-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
          />
        </PersistGate>
      </Provider>
    </>

  )
}

export default MyApp
